Parameters:
  Environment:
    Type: String
    Default: prod
  NetworkStackName:
    Type: String
    Default: networkStack
  BackendStackName:
    Type: String
    Default: backendStack
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for backend Instances
      VpcId: !ImportValue
        Fn::Sub: ${NetworkStackName}-VPCID
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-LB-SG
  AppELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref InstanceSecurityGroup

      Subnets:
        - !ImportValue
          Fn::Sub: ${NetworkStackName}-PublicSubnet1ID
        - !ImportValue
          Fn::Sub: ${NetworkStackName}-PublicSubnet2ID
        - !ImportValue
          Fn::Sub: ${NetworkStackName}-PublicSubnet3ID
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-ALB
  AppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /
      HealthCheckPort: 80
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      IpAddressType: ipv4
      Matcher: 
        HttpCode: "200,302"
      UnhealthyThresholdCount: 2
      Protocol: HTTP
      Port: 80
      VpcId: !ImportValue
        Fn::Sub: ${NetworkStackName}-VPCID
      TargetType: instance
      Targets:
        - Id: !ImportValue
            Fn::Sub: ${BackendStackName}-BackendInstance1ID
        - Id: !ImportValue
            Fn::Sub: ${BackendStackName}-BackendInstance2ID
        - Id: !ImportValue
            Fn::Sub: ${BackendStackName}-BackendInstance3ID
      Tags: 
      - Key: Name
        Value: !Sub ${Environment}-Backend-TG

  ELBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref AppELB
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref AppTargetGroup
      Tags:
        - Key: Name
          Value: !Sub ${Environment}-LB-Listener
Outputs:
  StackId:
    Description: The id of stack
    Value: !Sub ${AWS::StackName}
  BackendSecurityGroup:
    Description: The ID of the InstanceSecurityGroup
    Value: !Ref InstanceSecurityGroup
    Export:
      Name: !Sub ${AWS::StackName}-ELBSecurityGroupID
